### ISSUE TITLE
Open source softballbot?

### ISSUE THREAD

**Issue by amp343** [nowait-tools/docker-images#57]
These tools are pretty awesome, but I'm wondering if you would consider open-sourcing softballbot as well. Softballbot is an amazing piece of AI that immediately increases the morale of any organization. Thus, I believe it would be a boon to the industry -- no, the world -- if he were available for mass consumption*.

*<sup>or at least my personal download</sup>

**Comment by michaeljs1990** [comment]
+5

**Comment by ddelnano** [comment]
⚾️
